### ISSUE TITLE
doesn't support special characters in the directory name 

### ISSUE THREAD

**Issue by amycogniac** [Cogniac/cogniac-sdk-py#19]
when try to upload osaka gas data
amy (master *) osaka_gas $ cogupload orig_set2_class1_7gh '2_ÇxÇm/Class1' -r
\Authenticating...
Connecting to Cogniac system at https://api.cogniac.io/1
Osaka Gas (okcxdc6k39ja)
Traceback (most recent call last):
  File "/usr/local/bin/cogupload", line 99, in <module>
    results = pool.map(upload_and_associate, files)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 3: ordinal not in range(128)

**Comment by amycogniac** [comment]
it is the special characters in the directory name caused that. once I rename the directory to english characters, no issue

**Comment by wskish** [comment]
dup of https://github.com/Cogniac/cogniac-sdk-py/issues/37
